version: '3'

networks:
  redis-cluster-compose:
    driver: bridge

services:
  redis-node-1:
    image: redis:latest
    ports:
      - 7001:7001
    networks:
      - redis-cluster-compose
    hostname: redis-node-1
    volumes:
      - ./redis/7001:/redis
    command: redis-server /redis/redis.conf
  redis-node-2:
    image: redis:latest
    ports:
      - 7002:7002
    networks:
      - redis-cluster-compose
    hostname: redis-node-2
    volumes:
      - ./redis/7002:/redis
    command: redis-server /redis/redis.conf
  redis-node-3:
    image: redis:latest
    ports:
      - 7003:7003
    networks:
      - redis-cluster-compose
    hostname: redis-node-3
    volumes:
      - ./redis/7003:/redis
    command: redis-server /redis/redis.conf

  redis-node-4:
    image: redis:latest
    ports:
      - 7004:7004
    networks:
      - redis-cluster-compose
    hostname: redis-node-4
    volumes:
      - ./redis/7004:/redis
    command: redis-server /redis/redis.conf

  redis-node-5:
    image: redis:latest
    ports:
      - 7005:7005
    networks:
      - redis-cluster-compose
    hostname: redis-node-5
    volumes:
      - ./redis/7005:/redis
    command: redis-server /redis/redis.conf
  
  redis-node-6:
    image: redis:latest
    ports:
      - 7006:7006
    networks:
      - redis-cluster-compose
    hostname: redis-node-6
    volumes:
      - ./redis/7006:/redis
    command: redis-server /redis/redis.conf
  
  redis-cluster-creator:
    image: redis:latest
    ports:
      - 6999:6999
    networks:
      - redis-cluster-compose
    command: redis-cli  --cluster create redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005 redis-node-6:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
  
  redis-insight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    networks:
      - redis-cluster-compose
    volumes:
      - .redis/redisinsight:/db
    depends_on:
      - redis-cluster-creator